### ISSUE TITLE
npm run dev 跑不起来 http://localhost:8080/#/  是空白页面

### ISSUE THREAD

**Issue by forconz** [spezz07/Vue-CN-Node#1]
npm run dev 跑不起来 http://localhost:8080/#/  是空白页面
DONE  Compiled successfully in 8722ms                                                                          22:17:15

> Listening at http://localhost:8080

**Comment by spezz07** [comment]
@dongeast  现在应该没问题了，我在index.vue里面不小心多加了一个结束标签
```
 <div class="content-list" v-for="(i,index) in  indexData" :key='index'></div>
//　把后面这个‘</div>’删掉就好
```
